config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'dashboard#index'
  post 'filter', to: 'dashboard#filter'


  resources :areas
  resources :subareas
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :subareas

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { maximum: 100 }

end

app/models/filter.rb
class Filter
  include ActiveModel::Model

  attr_accessor :query, :type, :status

  def initialize(attributes={})
    @type = attributes[:type]
    @query = attributes[:query]

    if attributes[:status] == "1"
      @status = true
    else
      @status = false
    end
  end

end

app/models/subarea.rb
class Subarea < ActiveRecord::Base
  belongs_to :area

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:edit, :update, :show, :destroy]


  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:success] = "Area foi criada!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @area.update(area_params)
      flash[:success] = "Área atualizada com sucesso!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @area.destroy
    flash[:danger] = "Área Deletada!"
    redirect_to root_path
  end

  private

  def area_params
    params.require(:area).permit(:name, :status)
  end
  def set_area
    @area = Area.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @areas = Area.all
    @filter = Filter.new
  end

  def filter
    @filter = Filter.new(params[:filter])

    if @filter.type.eql? "SubArea"
      @result = Subarea.find_by(name: @filter.query, status: @filter.status)
    else
      @result = Area.find_by(name: @filter.query, status: @filter.status)
    end
  end
end

app/controllers/subareas_controller.rb
class SubareasController < ApplicationController
  before_action :set_subarea, only: [:edit, :update, :show, :destroy]

  def new
    @subarea = Subarea.new
  end

  def create
    @subarea = Subarea.new(subarea_params)
    if @subarea.save
      flash[:success] = "Subarea foi criada!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @subarea.update(area_params)
      flash[:success] = "Subárea atualizada com sucesso!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @subarea.destroy
    flash[:danger] = "SubÁrea Deletada!"
    redirect_to root_path
  end

  private

  def subarea_params
    params.require(:subarea).permit(:name, :status, :area_id)
  end
  def set_subarea
    @subarea = Subarea.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/areas/_form.html.erb
<%= render 'shared/errors', obj: @area %>

<div class="row">
  <div class="col-xs-12">
  <%= form_for(@area, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %><br>
      </div>
      <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nome da Área", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :status %><br>
      </div>
      <div class="col-sm-8">
          <%= f.check_box :status, checked: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>

    <div class="text-center">
      [ <%= link_to 'Cancelar inserção e voltar para o filtro', root_path %> ]
    </div>
  </div>
</div>

app/views/areas/edit.html.erb
<h1 class="text-center">Editar Área</h1>

<%= render 'form' %>

app/views/areas/new.html.erb
<h1 class="text-center">Cadastrar Área</h1>

<%= render 'form' %>

app/views/areas/show.html.erb
<h1><%= @area.name %></h1>

app/views/dashboard/filter.html.erb
<% if @result.nil? %>
  <h1 class="text-center">Nenhum resultado encontrado</h1>
<% else %>
  <h1 class="text-center"><%=@result.name%> existe!</h1>
<% end %>

app/views/dashboard/index.html.erb
<h1 class="text-center">Filtro</h1>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="filtro">
      <%= form_for(@filter, :html => {class: "form-filter", role: "form"}, url: filter_path) do |f| %>
      <div class="form-group">
        <div>
          <%= f.text_field :query, class: "form-control", placeholder: "Área" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8">
          <%= f.radio_button :type, "Area", checked: true %> Area <br>
          <%= f.radio_button :type, "SubArea" %> SubArea <br>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label">
          <%= f.label "Status" %>
        </div>
        <div>
          <%= f.check_box :status, checked: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Pesquisar", class: "btn btn-default btn-xs" %>
      </div>
      <% end %>
    </div>

    <table class="table table-striped table-bordered">
      <thead>
        <th>Área de conhecimento</th>
        <th>SubÁrea</th>
        <th>Acoes</th>
        <th>Status</th>
      </thead>
      <tbody>
        <% @areas.each do |area| %>
          <tr>
            <th><%= area.name %></th>
            <td></td>
            <td class="text-center">
              <%= link_to 'Editar', edit_area_path(area), class: "btn btn-xs btn-primary" %> |
              <%= link_to 'Deletar', area_path(area), method: :delete,
                                                        data: {confirm: "Você tem certeza?"},
                                                        class: "btn btn-xs btn-danger" %>
            </td>
            <% if area.status %>
            <td>Ativo</td>
            <% else %>
            <td>Inativo</td>
            <% end %>
          </tr>
          <% if area.subareas.any? %>
            <% area.subareas.each do |subarea| %>
              <tr>
                <th></th>
                <td><%= subarea.name %></td>
                <td class="text-center">
                  <%= link_to 'Editar', edit_subarea_path(subarea), class: "btn btn-xs btn-primary" %> |
                  <%= link_to 'Deletar', subarea_path(subarea), method: :delete,
                                                            data: {confirm: "Você tem certeza?"},
                                                            class: "btn btn-xs btn-danger" %>
                </td>
                <% if subarea.status %>
                <td>Ativo</td>
                <% else %>
                <td>Inativo</td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <p>
      <%= link_to 'Criar nova area', new_area_path, class: "btn btn-primary" %>
    </p>
    <p>
      <%= link_to 'Criar nova subarea', new_subarea_path, class: "btn btn-primary" %>
    </p>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 ">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaDeGestaoDeFornecedores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "erro") %>
            imperiram que fosse criado:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/subareas/_form.html.erb
<%= render 'shared/errors', obj: @subarea %>

<div class="row">
  <div class="col-xs-12">
  <%= form_for(@subarea, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :area_id %><br>
      </div>
      <div class="col-sm-8">
        <%= f.collection_select(:area_id, Area.all, :id, :name) %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %><br>
      </div>
      <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Nome da Subarea" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :status %><br>
      </div>
      <div class="col-sm-8">
          <%= f.check_box :status, checked: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  <% end %>

    <div class="text-center">
      [ <%= link_to 'Cancelar inserção e voltar para o filtro', root_path %> ]
    </div>
  </div>
</div>

app/views/subareas/edit.html.erb
<h1 class="text-center">Editar Subrea</h1>

<%= render 'form' %>

app/views/subareas/new.html.erb
<h1 class="text-center">Cadastrar Subárea</h1>

<%= render 'form' %>

app/views/subareas/show.html.erb
<h1><%= @subarea.name %></h1>